export const START_LOAD = '@ENTRIES-AND-EXPENSES/START_LOAD';
export const FETCH_RECORDS = '@ENTRIES-AND-EXPENSES/FETCH_RECORDS';
export const FIND_RECORD = '@ENTRIES-AND-EXPENSES/FIND-RECORD';
export const SAVE_RECORD = '@ENTRIES-AND-EXPENSES/FETCH_RECORDS';
export const ERROR = '@ENTRIES-AND-EXPENSES/ERROR';
